### ISSUE TITLE
Suggestions for consideration.

### ISSUE THREAD

**Issue by SimonGideon** [Kevo-hacker/Mobile-Version#6]
## HTML Basic Practices
In Microverse we are advice to used classes when giving reference to HTML elements. I will suggest to minimize the use of ids for semantics.

## Workflow
When arranging files in you project directory, Its my suggestion that you place images on a different directory e.g  `/images` or `/assets/img`

## Naming Convention
I think it works better when you have a basic practice of your naming system.
There are several I can point out:
1. camelCase
2. PascalCase
3. snake_case

## The UI
You Really kept much efforts 🎉🎉 on implementing the UI, and you did it 🎊🎊, just to point a little, the wifi 📶 and 🔋 this is part of device frames is not necessarily to be used in the design.

**Comment by Kelvin-Ben** [comment]
@SimonGideon ,thanks for the review,, it was not in my mind,, I will make sure I take the note when create div elements.
